# Generated by Django 5.0.7 on 2024-08-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('task_status', models.CharField(choices=[('Inprogress', 'Inprogress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending')], default='Pending', max_length=25)),
                ('task_deadline', models.DateTimeField()),
                ('task_created_date', models.DateTimeField(auto_now_add=True)),
                ('task_completed_date', models.DateTimeField()),
            ],
        ),
    ]
