# Generated by Django 5.0.7 on 2024-08-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_completed_date',
            field=models.DateTimeField(default=None),
        ),
    ]
